proj_v2/my_app/urls.py
from my_app import views
from django.conf.urls import url,include

app_name = 'my_app'

urlpatterns = [
    url(r'^register/',views.register,name='register'),
    url(r'^other/',views.other,name='other'),
    url(r'^user_login/$',views.user_login,name='user_login'),


]

proj_v2/proj_v2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from my_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^my_app/',include('my_app.urls')),
    url(r'^logout/$', views.user_logout,name='user_logout'),

]

proj_v2/my_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserInfo(models.Model):
    user =  models.OneToOneField(User)
    pic = models.ImageField(blank = True, upload_to='pics')
    my_link  = models.URLField(blank  = True)

    def __str__(self):
        return self.user.username
# Create your models here.

proj_v2/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from my_app.models import UserInfo


class UserForm(forms.ModelForm):

    password = forms.CharField(widget =  forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('pic','my_link')

proj_v2/my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm , UserInfoForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'my_app/index.html')
def other(request):
    return render(request,'my_app/other.html')
def register(request):
    is_registered = False
    user_form = UserForm()
    profile_form = UserInfoForm()

    if request.method =='POST':
        user_form = UserForm( data = request.POST)
        profile_form = UserInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'pic' in request.FILES:
                profile.pic = request.FILES['pic']

            profile.save()
            is_registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        print('NOT POST')
        user_form = UserForm()
        profile_form = UserInfoForm()
    return render(request,'my_app/register.html',{'user_form':user_form,'profile_form':profile_form,'is_registered':is_registered})

def user_login(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print('username {} and password {}'.format(username,password));
        user= authenticate(username = username, password = password)
        if user:
            print('authenticated')
            if user.is_active:
                print('{} is active'.format(username))
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                print('User Not active')
                return HttpResponse('User is not active')
        else:
            print('User Not authenticated')
            print('{} tried to login with pwd {}'.format(username,password))
            return HttpResponse('Invalid login supplied:/')
    else:
        print('not post')
        return render(request,'my_app/logon.html',{})

@login_required
def user_logout(request):
    print('user logging out')
    logout(request)
    return HttpResponseRedirect(reverse('index'))

proj_v2/templates/my_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li>
            <a class="navbar-brand" href="{% url 'index' %}">Index</a>
          </li>
          <li>
            <a class="navbar-brand" href="{% url 'my_app:register' %}">Register</a>
          </li>
          <li>
            <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% if user.is_authenticated %}
          <li>
            <a class="navbar-link" href="{% url 'user_logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a class="navbar-link" href="{% url 'my_app:user_login' %}">LogIN</a>
          </li>
          {% endif %}
        </ul>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

proj_v2/templates/my_app/index.html
<!DOCTYPE html>
{% extends 'my_app/base.html'%}
{% block body_block %}
<div class="contaner">
<h1>Hello from Index!</h1>
</div>
{% endblock %}

proj_v2/templates/my_app/logon.html
<!DOCTYPE html>
{% extends 'my_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Log in</h1>
  <form  action="{% url 'my_app:user_login' %}" method="post">
{%csrf_token%}

  <label for="username">User Name :</label>
  <input type="text" name="username" placeholder="Enter username">
  <label for="password">Password</label>
  <input type="password" name="password" >
  <input type="submit" class="btn btn-primary" value="Log In">
    </form>
</div>
{% endblock %}

proj_v2/templates/my_app/other.html
<!DOCTYPE html>
{% extends 'my_app/base.html'%}
{% block body_block %}
<div class="contaner">
<h1>Hello from other!</h1>
</div>
{% endblock %}

proj_v2/templates/my_app/register.html
<!DOCTYPE html>
{% extends 'my_app/base.html'%}
{% load staticfiles %}


{% block body_block %}
{%if is_registered%}

<div class="container">
  <div class="jumbotron">
    <h2>Thanks for registering</h2>
  </div>



</div>
{% else %}
<div class="container">
  <h2>Register Here</h2>
  <form enctype="multipart/form-data"  method="post">
      {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}
<input type="submit" class = "btn btn-primary" value="Send">
  </form>
</div>
{% endif %}
{% endblock %}